# Generated by Django 2.2 on 2020-06-09 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_auto_20200608_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_availabe', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospitals.Hospital')),
            ],
        ),
    ]
