# Generated by Django 2.2 on 2020-06-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0008_auto_20200612_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='SearchState',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTaluka',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('taluka', models.CharField(blank=True, max_length=400)),
            ],
        ),
    ]
