# Generated by Django 2.2 on 2020-06-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('street', models.CharField(blank=True, max_length=400)),
                ('landmark', models.CharField(blank=True, max_length=400)),
                ('locality', models.CharField(blank=True, max_length=400)),
                ('pincode', models.IntegerField()),
                ('landline', models.IntegerField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('facility_type', models.CharField(max_length=400)),
                ('state', models.CharField(max_length=400)),
                ('district', models.CharField(max_length=400)),
                ('taluka', models.CharField(max_length=400)),
                ('block', models.CharField(max_length=400)),
            ],
        ),
    ]
