# Generated by Django 2.2 on 2020-06-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='altitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='block',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='district',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='facility_type',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='pincode',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='state',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='taluka',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
