# Generated by Django 2.2 on 2020-06-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_auto_20200608_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='landline',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
