# Generated by Django 2.2 on 2020-06-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_pincode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pincode',
            new_name='SearchPincode',
        ),
    ]
