# Generated by Django 2.2 on 2020-06-17 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0009_searchdistrict_searchstate_searchtaluka'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdistrict',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.SearchState'),
        ),
        migrations.AddField(
            model_name='searchtaluka',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.SearchDistrict'),
        ),
        migrations.AddField(
            model_name='searchtaluka',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.SearchState'),
        ),
    ]
