# Generated by Django 2.2 on 2020-07-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_auto_20200617_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='bed_availabe',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
